import type {
  Lead,
  Call,
  Associate,
  ClientAllocation,
  WhatsAppConversation,
  FollowUp,
  Activity,
  TimelineEvent,
} from "@/lib/types";

// Realistic, self-consistent Dubai demo dataset. This is what the app shows
// when APP_MODE=demo (or when the live Google Sheet is not reachable), so a
// client demo always looks complete. Every ID here is cross-referenced
// (lead <-> call <-> whatsapp <-> follow-up <-> associate) so drilling into
// any record tells a coherent story.

const now = new Date("2026-08-17T11:15:00+04:00");
const iso = (offsetMinutes: number) => new Date(now.getTime() + offsetMinutes * 60000).toISOString();

export const demoAssociates: Associate[] = [
  {
    id: "assoc-1",
    employeeCode: "EMP-101",
    name: "Ahmed Khan",
    role: "Senior Property Specialist",
    tier: "Senior Specialist",
    status: "Active",
    availability: "Available",
    phone: "+971 50 123 4567",
    email: "ahmed.khan@onexproperties.ae",
    avatarUrl: null,
    territories: ["Dubai Marina", "Business Bay", "JBR", "Downtown Dubai"],
    propertyTypes: ["Apartment", "Penthouse"],
    purchasePurposes: ["Investment", "End-use"],
    budgetMin: 1_000_000,
    budgetMax: 5_000_000,
    languages: ["English", "Arabic", "Urdu"],
    maxActiveCapacity: 15,
    leadsAssigned: 42,
    hotLeads: 13,
    followUps: 18,
    currentActiveClients: 7,
    pendingAcceptanceCount: 1,
    historicalConversionRate: 22.4,
    averageResponseMinutes: 12,
    totalAssignedAllTime: 128,
    totalClosedAllTime: 29,
    performanceScore: 92,
    joiningDate: "2023-03-15",
    lastActivityAt: iso(-40),
    lastAssignedAt: iso(-65),
    notes: "Top converter for Marina & Business Bay investment units.",
  },
  {
    id: "assoc-2",
    employeeCode: "EMP-102",
    name: "Anil Kumar",
    role: "Senior Property Specialist",
    tier: "Senior Specialist",
    status: "Active",
    availability: "Available",
    phone: "+971 50 234 5678",
    email: "anil.kumar@onexproperties.ae",
    avatarUrl: null,
    territories: ["Palm Jumeirah", "Dubai Hills Estate", "Emirates Hills"],
    propertyTypes: ["Villa", "Townhouse", "Penthouse"],
    purchasePurposes: ["End-use", "Investment"],
    budgetMin: 4_000_000,
    budgetMax: 25_000_000,
    languages: ["English", "Hindi"],
    maxActiveCapacity: 12,
    leadsAssigned: 37,
    hotLeads: 9,
    followUps: 11,
    currentActiveClients: 6,
    pendingAcceptanceCount: 0,
    historicalConversionRate: 19.8,
    averageResponseMinutes: 16,
    totalAssignedAllTime: 94,
    totalClosedAllTime: 19,
    performanceScore: 88,
    joiningDate: "2023-06-01",
    lastActivityAt: iso(-120),
    lastAssignedAt: iso(-40),
    notes: "Luxury villa & Palm Jumeirah waterfront specialist.",
  },
  {
    id: "assoc-3",
    employeeCode: "EMP-103",
    name: "Fatima Noor",
    role: "Property Specialist",
    tier: "Property Specialist",
    status: "Away",
    availability: "Busy",
    phone: "+971 50 345 6789",
    email: "fatima.noor@onexproperties.ae",
    avatarUrl: null,
    territories: ["Jumeirah Village Circle", "Jumeirah Golf Estates", "Town Square"],
    propertyTypes: ["Townhouse", "Apartment", "Studio"],
    purchasePurposes: ["End-use", "Investment"],
    budgetMin: 700_000,
    budgetMax: 3_500_000,
    languages: ["English", "Arabic", "French"],
    maxActiveCapacity: 15,
    leadsAssigned: 29,
    hotLeads: 6,
    followUps: 8,
    currentActiveClients: 5,
    pendingAcceptanceCount: 0,
    historicalConversionRate: 16.5,
    averageResponseMinutes: 24,
    totalAssignedAllTime: 72,
    totalClosedAllTime: 12,
    performanceScore: 81,
    joiningDate: "2024-01-10",
    lastActivityAt: iso(-320),
    lastAssignedAt: iso(-500),
    notes: "Specializes in family townhouses & JVC communities.",
  },
  {
    id: "assoc-4",
    employeeCode: "EMP-104",
    name: "James Carter",
    role: "Property Specialist",
    tier: "Junior Specialist",
    status: "Offline",
    availability: "Offline",
    phone: "+971 50 456 7890",
    email: "james.carter@onexproperties.ae",
    avatarUrl: null,
    territories: ["Downtown Dubai", "DIFC", "City Walk"],
    propertyTypes: ["Apartment", "Studio"],
    purchasePurposes: ["Investment", "End-use"],
    budgetMin: 1_200_000,
    budgetMax: 4_000_000,
    languages: ["English"],
    maxActiveCapacity: 10,
    leadsAssigned: 21,
    hotLeads: 3,
    followUps: 4,
    currentActiveClients: 2,
    pendingAcceptanceCount: 0,
    historicalConversionRate: 14.0,
    averageResponseMinutes: 35,
    totalAssignedAllTime: 45,
    totalClosedAllTime: 6,
    performanceScore: 74,
    joiningDate: "2024-04-01",
    lastActivityAt: iso(-900),
    lastAssignedAt: iso(-1200),
    notes: "Focuses on Downtown high-rise apartments and short-term rental yields.",
  },
];

const rahulTranscript = [
  { speaker: "SOFIA", role: "AI Agent" as const, text: "Hi, am I speaking with Rahul?", timestamp: "00:02" },
  { speaker: "RAHUL", role: "Specialist" as const, text: "Yes, speaking.", timestamp: "00:05" },
  { speaker: "SOFIA", role: "AI Agent" as const, text: "Great, thanks for your enquiry. Are you mainly looking to buy in Dubai?", timestamp: "00:08" },
  { speaker: "RAHUL", role: "Specialist" as const, text: "Yes, I'm looking around Dubai Marina, maybe Business Bay too.", timestamp: "00:14" },
  { speaker: "SOFIA", role: "AI Agent" as const, text: "Understood. Is this for investment or for you to live in?", timestamp: "00:20" },
  { speaker: "RAHUL", role: "Specialist" as const, text: "It's an investment. I'd want to rent it out.", timestamp: "00:25" },
  { speaker: "SOFIA", role: "AI Agent" as const, text: "What budget range should I share with the specialist?", timestamp: "00:31" },
  { speaker: "RAHUL", role: "Specialist" as const, text: "Somewhere between one and a half to two million dirhams.", timestamp: "00:37" },
  { speaker: "SOFIA", role: "AI Agent" as const, text: "And a rough timeline — are you looking to move in the next few months?", timestamp: "00:44" },
  { speaker: "RAHUL", role: "Specialist" as const, text: "Yes, ideally within 60 days if the right unit comes up.", timestamp: "00:50" },
  { speaker: "SOFIA", role: "AI Agent" as const, text: "Perfect, I'll pass this to one of our specialists who covers Marina and Business Bay. Would you prefer a callback this evening or tomorrow morning?", timestamp: "00:58" },
  { speaker: "RAHUL", role: "Specialist" as const, text: "Tomorrow morning works better, around 11.", timestamp: "01:06" },
  { speaker: "SOFIA", role: "AI Agent" as const, text: "Noted — 11 AM tomorrow. Thanks Rahul, you'll also get a WhatsApp confirming this.", timestamp: "01:12" },
];

export const demoLeads: Lead[] = [
  {
    id: "lead-1",
    leadId: "LEAD-1042",
    buyerName: "Rahul Sharma",
    phone: "+971 50 987 6543",
    source: "Property Finder",
    country: "United Arab Emirates",
    city: "Dubai",
    preferredArea: "Dubai Marina / Business Bay",
    propertyType: "Apartment",
    bedrooms: "2 BR",
    purchasePurpose: "Investment",
    budgetMin: 1_500_000,
    budgetMax: 2_000_000,
    currency: "AED",
    purchaseTimeline: "Within 60 days",
    keyRequirements: "Rental yield, near metro, sea view preferred",
    status: "Follow-up",
    temperature: "HOT",
    qualificationScore: 86,
    qualificationCompleteness: 92,
    brokerFollowupRequested: true,
    preferredCallbackTime: "Tomorrow, 11:00 AM",
    assignedAssociateId: "assoc-1",
    createdAt: iso(-72),
    updatedAt: iso(-65),
    lastContactAt: iso(-68),
    nextAction: "Specialist callback at 11:00 AM",
    callOutcome: "Qualified — Specialist follow-up requested",
    callSummary:
      "Rahul is an investor targeting Dubai Marina or Business Bay, budget AED 1.5–2M, wants strong rental yield and metro proximity. Requested a callback tomorrow at 11 AM.",
  },
  {
    id: "lead-2",
    leadId: "LEAD-1041",
    buyerName: "Ahmed Khan",
    phone: "+971 55 234 1187",
    source: "Instagram Ad",
    country: "United Arab Emirates",
    city: "Dubai",
    preferredArea: "JVC",
    propertyType: "Studio",
    bedrooms: "Studio",
    purchasePurpose: "Investment",
    budgetMin: 500_000,
    budgetMax: 750_000,
    currency: "AED",
    purchaseTimeline: "Not provided",
    keyRequirements: "Not provided",
    status: "New",
    temperature: "UNQUALIFIED",
    qualificationScore: null,
    qualificationCompleteness: 10,
    brokerFollowupRequested: false,
    preferredCallbackTime: null,
    assignedAssociateId: null,
    createdAt: iso(-30),
    updatedAt: iso(-30),
    lastContactAt: iso(-28),
    nextAction: "Send WhatsApp recovery message",
    callOutcome: "No Answer",
    callSummary: null,
  },
  {
    id: "lead-3",
    leadId: "LEAD-1039",
    buyerName: "Priya Das",
    phone: "+971 52 776 4432",
    source: "Website Enquiry",
    country: "United Arab Emirates",
    city: "Dubai",
    preferredArea: "Downtown Dubai",
    propertyType: "Apartment",
    bedrooms: "1 BR",
    purchasePurpose: "End-use",
    budgetMin: 1_800_000,
    budgetMax: 2_200_000,
    currency: "AED",
    purchaseTimeline: "3–6 months",
    keyRequirements: "Burj Khalifa view, high floor",
    status: "Qualified",
    temperature: "WARM",
    qualificationScore: 71,
    qualificationCompleteness: 80,
    brokerFollowupRequested: true,
    preferredCallbackTime: "This week",
    assignedAssociateId: null,
    createdAt: iso(-200),
    updatedAt: iso(-150),
    lastContactAt: iso(-150),
    nextAction: "Assign a property specialist",
    callOutcome: "Qualified — Specialist follow-up requested",
    callSummary:
      "Priya wants a 1BR in Downtown Dubai with a view, end-use, budget AED 1.8–2.2M within 3–6 months. Qualified but not yet assigned to a specialist.",
  },
  {
    id: "lead-4",
    leadId: "LEAD-1036",
    buyerName: "Omar Ali",
    phone: "+971 56 112 9080",
    source: "Referral",
    country: "United Arab Emirates",
    city: "Dubai",
    preferredArea: "Palm Jumeirah",
    propertyType: "Villa",
    bedrooms: "4 BR",
    purchasePurpose: "End-use",
    budgetMin: 8_000_000,
    budgetMax: 10_000_000,
    currency: "AED",
    purchaseTimeline: "Flexible",
    keyRequirements: "Private beach access, renovated",
    status: "Follow-up",
    temperature: "HOT",
    qualificationScore: 90,
    qualificationCompleteness: 95,
    brokerFollowupRequested: true,
    preferredCallbackTime: "Callback requested — see schedule",
    assignedAssociateId: "assoc-2",
    createdAt: iso(-400),
    updatedAt: iso(-40),
    lastContactAt: iso(-40),
    nextAction: "View callback schedule",
    callOutcome: "Callback Requested",
    callSummary:
      "Omar is looking for a 4BR villa on Palm Jumeirah, budget AED 8–10M, end-use. Specialist call attempted, buyer requested a callback at a specific time.",
  },
  {
    id: "lead-5",
    leadId: "LEAD-1030",
    buyerName: "Sara Al Mansoori",
    phone: "+971 50 665 2214",
    source: "Property Finder",
    country: "United Arab Emirates",
    city: "Dubai",
    preferredArea: "Jumeirah Village Circle",
    propertyType: "Townhouse",
    bedrooms: "3 BR",
    purchasePurpose: "End-use",
    budgetMin: 2_400_000,
    budgetMax: 2_800_000,
    currency: "AED",
    purchaseTimeline: "Within 90 days",
    keyRequirements: "Community with schools nearby",
    status: "Contacted",
    temperature: "WARM",
    qualificationScore: 64,
    qualificationCompleteness: 70,
    brokerFollowupRequested: false,
    preferredCallbackTime: null,
    assignedAssociateId: "assoc-3",
    createdAt: iso(-600),
    updatedAt: iso(-500),
    lastContactAt: iso(-500),
    nextAction: "Follow up in 2 days",
    callOutcome: "Qualified",
    callSummary: "Sara wants a 3BR townhouse in JVC near good schools, budget AED 2.4–2.8M.",
  },
  {
    id: "lead-6",
    leadId: "LEAD-1028",
    buyerName: "Michael Chen",
    phone: "+971 54 887 3321",
    source: "Google Ads",
    country: "United Arab Emirates",
    city: "Dubai",
    preferredArea: "Not provided",
    propertyType: "Not provided",
    bedrooms: null,
    purchasePurpose: "Not provided",
    budgetMin: null,
    budgetMax: null,
    currency: "AED",
    purchaseTimeline: null,
    keyRequirements: null,
    status: "New",
    temperature: "UNQUALIFIED",
    qualificationScore: null,
    qualificationCompleteness: 0,
    brokerFollowupRequested: false,
    preferredCallbackTime: null,
    assignedAssociateId: null,
    createdAt: iso(-10),
    updatedAt: iso(-10),
    lastContactAt: null,
    nextAction: "AI call pending",
    callOutcome: null,
    callSummary: null,
  },
  {
    id: "lead-7",
    leadId: "LEAD-1020",
    buyerName: "Layla Haddad",
    phone: "+971 55 990 1123",
    source: "Website Enquiry",
    country: "United Arab Emirates",
    city: "Dubai",
    preferredArea: "Dubai Hills Estate",
    propertyType: "Villa",
    bedrooms: "5 BR",
    purchasePurpose: "End-use",
    budgetMin: 6_000_000,
    budgetMax: 7_500_000,
    currency: "AED",
    purchaseTimeline: "6–12 months",
    keyRequirements: "Golf course view",
    status: "Closed",
    temperature: "HOT",
    qualificationScore: 88,
    qualificationCompleteness: 100,
    brokerFollowupRequested: false,
    preferredCallbackTime: null,
    assignedAssociateId: "assoc-2",
    createdAt: iso(-4000),
    updatedAt: iso(-3000),
    lastContactAt: iso(-3000),
    nextAction: "Deal closed",
    callOutcome: "Qualified",
    callSummary: "Layla purchased a 5BR villa in Dubai Hills Estate. Deal closed.",
  },
  {
    id: "lead-8",
    leadId: "LEAD-1044",
    buyerName: "Anil Kumar",
    phone: "+971 52 331 8890",
    source: "Instagram Ad",
    country: "United Arab Emirates",
    city: "Dubai",
    preferredArea: "Business Bay",
    propertyType: "Apartment",
    bedrooms: "1 BR",
    purchasePurpose: "Investment",
    budgetMin: 1_100_000,
    budgetMax: 1_300_000,
    currency: "AED",
    purchaseTimeline: "Not provided",
    keyRequirements: "Not provided",
    status: "Contacted",
    temperature: "COLD",
    qualificationScore: 38,
    qualificationCompleteness: 45,
    brokerFollowupRequested: false,
    preferredCallbackTime: null,
    assignedAssociateId: null,
    createdAt: iso(-90),
    updatedAt: iso(-80),
    lastContactAt: iso(-80),
    nextAction: "Low priority — monitor",
    callOutcome: "Not Interested",
    callSummary: "Buyer was noncommittal, said just browsing for now.",
  },
];

export const demoCalls: Call[] = [
  {
    id: "call-1",
    callId: "CALL-88231",
    analysisId: "ANALYSIS-44120",
    leadId: "lead-1",
    agentName: "Sofia",
    callerRole: "AI Agent",
    startedAt: iso(-72),
    endedAt: iso(-70),
    durationSeconds: 192,
    status: "Answered",
    outcome: "Qualified — Specialist follow-up requested",
    recordingUrl: null,
    transcript: rahulTranscript,
    summary:
      "Rahul is an investor targeting Dubai Marina or Business Bay, budget AED 1.5–2M, wants strong rental yield and metro proximity. Requested a callback tomorrow at 11 AM.",
    temperature: "HOT",
    score: 86,
    scoreBreakdown: [
      { label: "Budget clarity", score: 12, max: 15 },
      { label: "Timeline", score: 18, max: 20 },
      { label: "Requirements", score: 13, max: 15 },
      { label: "Location", score: 10, max: 10 },
      { label: "Purchase intent", score: 18, max: 20 },
      { label: "Follow-up willingness", score: 9, max: 10 },
      { label: "Completeness", score: 6, max: 10 },
    ],
    recommendedNextAction: "Assign a property specialist and follow up within the requested callback window.",
  },
  {
    id: "call-2",
    callId: "CALL-88240",
    analysisId: null,
    leadId: "lead-2",
    agentName: "Sofia",
    callerRole: "AI Agent",
    startedAt: iso(-30),
    endedAt: iso(-30),
    durationSeconds: 0,
    status: "No Answer",
    outcome: "No Answer",
    recordingUrl: null,
    transcript: null,
    summary: null,
    temperature: null,
    score: null,
    scoreBreakdown: null,
    recommendedNextAction: "Send a WhatsApp recovery message and retry the call later today.",
  },
  {
    id: "call-3",
    callId: "CALL-88190",
    analysisId: "ANALYSIS-44088",
    leadId: "lead-3",
    agentName: "Sofia",
    callerRole: "AI Agent",
    startedAt: iso(-200),
    endedAt: iso(-197),
    durationSeconds: 165,
    status: "Answered",
    outcome: "Qualified — Specialist follow-up requested",
    recordingUrl: null,
    transcript: [
      { speaker: "SOFIA", role: "AI Agent", text: "Hi, is this Priya?", timestamp: "00:02" },
      { speaker: "PRIYA", role: "Specialist", text: "Yes, hi.", timestamp: "00:04" },
      { speaker: "SOFIA", role: "AI Agent", text: "Thanks for your enquiry about Downtown Dubai. Is this to live in or an investment?", timestamp: "00:09" },
      { speaker: "PRIYA", role: "Specialist", text: "I'd live in it myself, ideally with a Burj Khalifa view.", timestamp: "00:16" },
      { speaker: "SOFIA", role: "AI Agent", text: "Great — and your budget range?", timestamp: "00:21" },
      { speaker: "PRIYA", role: "Specialist", text: "Around 1.8 to 2.2 million.", timestamp: "00:26" },
    ],
    summary: "Priya wants a 1BR in Downtown Dubai with a view, end-use, budget AED 1.8–2.2M within 3–6 months.",
    temperature: "WARM",
    score: 71,
    scoreBreakdown: [
      { label: "Budget clarity", score: 13, max: 15 },
      { label: "Timeline", score: 14, max: 20 },
      { label: "Requirements", score: 12, max: 15 },
      { label: "Location", score: 10, max: 10 },
      { label: "Purchase intent", score: 14, max: 20 },
      { label: "Follow-up willingness", score: 5, max: 10 },
      { label: "Completeness", score: 3, max: 10 },
    ],
    recommendedNextAction: "Assign a property specialist covering Downtown Dubai.",
  },
  {
    id: "call-4",
    callId: "CALL-88300",
    analysisId: null,
    leadId: "lead-4",
    agentName: "Anil Kumar",
    callerRole: "Specialist",
    startedAt: iso(-40),
    endedAt: iso(-40),
    durationSeconds: 0,
    status: "No Answer",
    outcome: "No Answer",
    recordingUrl: null,
    transcript: null,
    summary: null,
    temperature: "HOT",
    score: 90,
    scoreBreakdown: null,
    recommendedNextAction: "Send a WhatsApp follow-up and offer to reschedule the callback.",
  },
];

export const demoConversations: WhatsAppConversation[] = [
  {
    id: "wa-1",
    leadId: "lead-1",
    leadName: "Rahul Sharma",
    phone: "+971 50 987 6543",
    lastMessage: "Perfect, see you at 11.",
    lastMessageAt: iso(-60),
    unread: false,
    scenario: "qualified_confirmation",
    messages: [
      {
        id: "m1",
        conversationId: "wa-1",
        direction: "outgoing",
        text:
          "Hi Rahul, thanks for speaking with Sofia. Summary: 2BR apartment, Dubai Marina/Business Bay, AED 1.5–2M, investment. Ahmed Khan will call you tomorrow at 11:00 AM.",
        timestamp: iso(-68),
        status: "read",
      },
      { id: "m2", conversationId: "wa-1", direction: "incoming", text: "Perfect, see you at 11.", timestamp: iso(-60), status: "read" },
    ],
  },
  {
    id: "wa-2",
    leadId: "lead-2",
    leadName: "Ahmed Khan",
    phone: "+971 55 234 1187",
    lastMessage: "We tried calling but couldn't reach you...",
    lastMessageAt: iso(-29),
    unread: true,
    scenario: "no_answer_recovery",
    messages: [
      {
        id: "m3",
        conversationId: "wa-2",
        direction: "outgoing",
        text: "Hi, we tried calling but couldn't reach you. Reply here and we'll help with your studio enquiry in JVC.",
        timestamp: iso(-29),
        status: "delivered",
      },
    ],
  },
  {
    id: "wa-3",
    leadId: "lead-4",
    leadName: "Omar Ali",
    phone: "+971 56 112 9080",
    lastMessage: "Our specialist tried calling — when's a good time?",
    lastMessageAt: iso(-39),
    unread: true,
    scenario: "specialist_no_answer",
    messages: [
      {
        id: "m4",
        conversationId: "wa-3",
        direction: "outgoing",
        text: "Hi Omar, Anil Kumar tried calling about the Palm Jumeirah villa. When's a good time to reach you?",
        timestamp: iso(-39),
        status: "sent",
      },
    ],
  },
];

export const demoFollowUps: FollowUp[] = [
  { id: "fu-1", leadId: "lead-1", leadName: "Rahul Sharma", temperature: "HOT", associateId: "assoc-1", scheduledAt: iso(1260), status: "Today", notes: "Callback requested by buyer" },
  { id: "fu-2", leadId: "lead-4", leadName: "Omar Ali", temperature: "HOT", associateId: "assoc-2", scheduledAt: iso(180), status: "Today", notes: "Retry after no answer" },
  { id: "fu-3", leadId: "lead-3", leadName: "Priya Das", temperature: "WARM", associateId: null, scheduledAt: iso(2880), status: "Upcoming", notes: "Needs associate assignment first" },
  { id: "fu-4", leadId: "lead-5", leadName: "Sara Al Mansoori", temperature: "WARM", associateId: "assoc-3", scheduledAt: iso(-200), status: "Overdue", notes: "2 days overdue" },
  { id: "fu-5", leadId: "lead-7", leadName: "Layla Haddad", temperature: "HOT", associateId: "assoc-2", scheduledAt: iso(-3000), status: "Completed", notes: "Deal closed" },
];

export const demoActivity: Activity[] = [
  { id: "act-1", timestamp: iso(-5), type: "lead_created", label: "New lead received", leadId: "lead-6", leadName: "Michael Chen" },
  { id: "act-2", timestamp: iso(-29), type: "whatsapp_sent", label: "WhatsApp recovery message sent", leadId: "lead-2", leadName: "Ahmed Khan" },
  { id: "act-3", timestamp: iso(-30), type: "specialist_call_unanswered", label: "AI call — no answer", leadId: "lead-2", leadName: "Ahmed Khan" },
  { id: "act-4", timestamp: iso(-39), type: "whatsapp_sent", label: "Specialist follow-up WhatsApp sent", leadId: "lead-4", leadName: "Omar Ali" },
  { id: "act-5", timestamp: iso(-40), type: "specialist_call_unanswered", label: "Specialist call attempted — unanswered", leadId: "lead-4", leadName: "Omar Ali" },
  { id: "act-6", timestamp: iso(-60), type: "whatsapp_replied", label: "WhatsApp confirmation replied", leadId: "lead-1", leadName: "Rahul Sharma" },
  { id: "act-7", timestamp: iso(-68), type: "whatsapp_sent", label: "WhatsApp confirmation sent", leadId: "lead-1", leadName: "Rahul Sharma" },
  { id: "act-8", timestamp: iso(-69), type: "lead_qualified", label: "Lead qualified — HOT", leadId: "lead-1", leadName: "Rahul Sharma" },
  { id: "act-9", timestamp: iso(-70), type: "analysis_completed", label: "AI analysis completed", leadId: "lead-1", leadName: "Rahul Sharma" },
  { id: "act-10", timestamp: iso(-72), type: "call_started", label: "AI call completed", leadId: "lead-1", leadName: "Rahul Sharma" },
];

export const demoAllocations: ClientAllocation[] = [
  {
    id: "alloc-1",
    leadId: "lead-1",
    leadName: "Rahul Sharma",
    associateId: "assoc-1",
    associateName: "Ahmed Khan",
    matchScore: 92,
    matchFactors: [
      { signal: "Location", score: 30, maxScore: 30, matched: true, detail: "Specialist covers Dubai Marina & Business Bay" },
      { signal: "PropertyType", score: 20, maxScore: 20, matched: true, detail: "Specialist in Apartment properties" },
      { signal: "Budget", score: 20, maxScore: 20, matched: true, detail: "Deal budget aligns with specialist tier" },
      { signal: "Capacity", score: 11, maxScore: 15, matched: true, detail: "Balanced workload (7/15 clients)" },
      { signal: "Performance", score: 10, maxScore: 10, matched: true, detail: "Top conversion performer (22.4% conv)" },
      { signal: "ResponseTime", score: 5, maxScore: 5, matched: true, detail: "Immediate availability (<15m avg response)" },
    ],
    allocationMethod: "RuleEngine",
    status: "Accepted",
    isCurrent: true,
    recommendedAt: iso(-69),
    assignedAt: iso(-65),
    acceptDeadlineAt: iso(-35),
    acceptedAt: iso(-60),
    firstContactDeadlineAt: iso(55),
    firstContactAt: null,
    completedAt: null,
    reassignedFromAssociateId: "assoc-4",
    reassignmentReason: "Specialist was offline",
    declineReason: null,
    outcomeNotes: "Buyer confirmed 11:00 AM morning callback.",
    createdAt: iso(-69),
    updatedAt: iso(-60),
  },
  {
    id: "alloc-old-1",
    leadId: "lead-1",
    leadName: "Rahul Sharma",
    associateId: "assoc-4",
    associateName: "James Carter",
    matchScore: 68,
    matchFactors: [
      { signal: "Location", score: 20, maxScore: 30, matched: true, detail: "Covers Business Bay adjacent" },
      { signal: "PropertyType", score: 20, maxScore: 20, matched: true, detail: "Specialist in Apartment properties" },
      { signal: "Budget", score: 15, maxScore: 20, matched: true, detail: "Within budget range" },
      { signal: "Capacity", score: 15, maxScore: 15, matched: true, detail: "High bandwidth (2/10 clients)" },
      { signal: "Performance", score: 7, maxScore: 10, matched: true, detail: "Standard conversion (14%)" },
      { signal: "ResponseTime", score: 0, maxScore: 5, matched: false, detail: "Specialist is currently offline" },
    ],
    allocationMethod: "RuleEngine",
    status: "Reassigned",
    isCurrent: false,
    recommendedAt: iso(-70),
    assignedAt: iso(-69),
    acceptDeadlineAt: iso(-39),
    acceptedAt: null,
    firstContactDeadlineAt: null,
    firstContactAt: null,
    completedAt: null,
    reassignedFromAssociateId: null,
    reassignmentReason: "Auto-reassigned due to offline specialist status",
    declineReason: null,
    outcomeNotes: "Auto-routed to Ahmed Khan",
    createdAt: iso(-70),
    updatedAt: iso(-65),
  },
  {
    id: "alloc-2",
    leadId: "lead-4",
    leadName: "Omar Ali",
    associateId: "assoc-2",
    associateName: "Anil Kumar",
    matchScore: 94,
    matchFactors: [
      { signal: "Location", score: 30, maxScore: 30, matched: true, detail: "Specialist covers Palm Jumeirah luxury villas" },
      { signal: "PropertyType", score: 20, maxScore: 20, matched: true, detail: "Specialist in Villa properties" },
      { signal: "Budget", score: 20, maxScore: 20, matched: true, detail: "Deal budget aligns with specialist tier (AED 8-10M)" },
      { signal: "Capacity", score: 11, maxScore: 15, matched: true, detail: "Balanced workload (6/12 clients)" },
      { signal: "Performance", score: 9, maxScore: 10, matched: true, detail: "High performance score (88/100)" },
      { signal: "ResponseTime", score: 4, maxScore: 5, matched: true, detail: "Available for new dispatch" },
    ],
    allocationMethod: "AdminManual",
    status: "Contacted",
    isCurrent: true,
    recommendedAt: iso(-300),
    assignedAt: iso(-250),
    acceptDeadlineAt: iso(-220),
    acceptedAt: iso(-240),
    firstContactDeadlineAt: iso(-120),
    firstContactAt: iso(-40),
    completedAt: null,
    reassignedFromAssociateId: null,
    reassignmentReason: null,
    declineReason: null,
    outcomeNotes: "Specialist call placed; follow-up WhatsApp sent.",
    createdAt: iso(-300),
    updatedAt: iso(-40),
  },
  {
    id: "alloc-3",
    leadId: "lead-5",
    leadName: "Sara Al Mansoori",
    associateId: "assoc-3",
    associateName: "Fatima Noor",
    matchScore: 89,
    matchFactors: [
      { signal: "Location", score: 30, maxScore: 30, matched: true, detail: "Specialist covers JVC family communities" },
      { signal: "PropertyType", score: 20, maxScore: 20, matched: true, detail: "Specialist in Townhouse properties" },
      { signal: "Budget", score: 20, maxScore: 20, matched: true, detail: "Budget AED 2.4-2.8M within primary band" },
      { signal: "Capacity", score: 11, maxScore: 15, matched: true, detail: "Balanced workload (5/15 clients)" },
      { signal: "Performance", score: 7, maxScore: 10, matched: true, detail: "Solid conversion record (16.5%)" },
      { signal: "ResponseTime", score: 2, maxScore: 5, matched: false, detail: "Specialist is currently busy" },
    ],
    allocationMethod: "RuleEngine",
    status: "Accepted",
    isCurrent: true,
    recommendedAt: iso(-550),
    assignedAt: iso(-520),
    acceptDeadlineAt: iso(-490),
    acceptedAt: iso(-510),
    firstContactDeadlineAt: iso(-390),
    firstContactAt: null,
    completedAt: null,
    reassignedFromAssociateId: null,
    reassignmentReason: null,
    declineReason: null,
    outcomeNotes: "Follow-up due.",
    createdAt: iso(-550),
    updatedAt: iso(-510),
  },
  {
    id: "alloc-4",
    leadId: "lead-7",
    leadName: "Layla Haddad",
    associateId: "assoc-2",
    associateName: "Anil Kumar",
    matchScore: 96,
    matchFactors: [
      { signal: "Location", score: 30, maxScore: 30, matched: true, detail: "Specialist covers Dubai Hills Estate" },
      { signal: "PropertyType", score: 20, maxScore: 20, matched: true, detail: "Specialist in Villa properties" },
      { signal: "Budget", score: 20, maxScore: 20, matched: true, detail: "Deal budget AED 6-7.5M aligns" },
      { signal: "Capacity", score: 11, maxScore: 15, matched: true, detail: "Balanced workload" },
      { signal: "Performance", score: 10, maxScore: 10, matched: true, detail: "Top conversion performer" },
      { signal: "ResponseTime", score: 5, maxScore: 5, matched: true, detail: "Available for dispatch" },
    ],
    allocationMethod: "RuleEngine",
    status: "Completed",
    isCurrent: true,
    recommendedAt: iso(-3800),
    assignedAt: iso(-3750),
    acceptDeadlineAt: iso(-3720),
    acceptedAt: iso(-3740),
    firstContactDeadlineAt: iso(-3620),
    firstContactAt: iso(-3700),
    completedAt: iso(-3000),
    reassignedFromAssociateId: null,
    reassignmentReason: null,
    declineReason: null,
    outcomeNotes: "Deal successfully closed for 5BR villa.",
    createdAt: iso(-3800),
    updatedAt: iso(-3000),
  },
];

export function buildDemoTimeline(leadId: string): TimelineEvent[] {
  if (leadId === "lead-1") {
    return [
      { id: "t1", leadId, timestamp: iso(-74), type: "lead_created", label: "Lead created", detail: "Source: Property Finder" },
      { id: "t2", leadId, timestamp: iso(-72), type: "call_started", label: "AI call started" },
      { id: "t3", leadId, timestamp: iso(-70), type: "call_completed", label: "Call completed", detail: "3:12 duration" },
      { id: "t4", leadId, timestamp: iso(-70), type: "analysis_completed", label: "AI analysis completed" },
      { id: "t5", leadId, timestamp: iso(-69), type: "lead_qualified", label: "Lead qualified — HOT", detail: "Score 86/100" },
      { id: "t6", leadId, timestamp: iso(-69), type: "followup_requested", label: "Follow-up requested" },
      { id: "t7", leadId, timestamp: iso(-68), type: "whatsapp_sent", label: "WhatsApp confirmation sent" },
      { id: "t8", leadId, timestamp: iso(-60), type: "whatsapp_replied", label: "Buyer replied on WhatsApp" },
      { id: "t9", leadId, timestamp: iso(-65), type: "associate_assigned", label: "Associate assigned", detail: "Ahmed Khan" },
      { id: "t10", leadId, timestamp: iso(1260), type: "callback_scheduled", label: "Specialist callback scheduled", detail: "Tomorrow, 11:00 AM" },
    ];
  }
  return [
    { id: "t1", leadId, timestamp: iso(-100), type: "lead_created", label: "Lead created" },
    { id: "t2", leadId, timestamp: iso(-90), type: "call_started", label: "AI call started" },
    { id: "t3", leadId, timestamp: iso(-90), type: "call_completed", label: "Call completed" },
  ];
}
